name: Check & Deploy
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'
      - name: Setup pipenv
        run: |
          sudo pip install pipenv --upgrade
          pipenv --python 3.9
          pipenv install -d
      - name: Lint
        run: make lint
      - name: Test
        run: make test
  deploy:
    needs: check
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENVIRONMENT_SECRET_ID: investment-automation-environment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'
      - name: Setup pipenv
        run: |
          sudo pip install pipenv --upgrade
          pipenv --python 3.9
          pipenv install -d
      - name: Setup AWS CDK
        run: |
          curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash -
          sudo apt-get -y -qq install nodejs
          sudo npm i -g aws-cdk
      - name: Deploy
        run: |
          cdk deploy --require-approval never --verbose
